from sense_hat import SenseHat
import time

sense = SenseHat()
sense.low_light = True

green = (0, 255, 0)
yellow = (255, 255, 0)
blue = (0, 0, 255)
red = (255, 0, 0)
white = (255, 255, 255)
nothing = (0, 0, 0)
pink = (255, 105, 180)
zeissblue = (20, 30, 255)  #20,30,140

sense.set_pixel(0,0, zeissblue)
sense.set_pixel(0,1, zeissblue)
sense.set_pixel(0,2, zeissblue)
sense.set_pixel(0,3, zeissblue)
sense.set_pixel(0,4, zeissblue)
sense.set_pixel(0,5, zeissblue)
sense.set_pixel(0,6, zeissblue)
sense.set_pixel(0,7, zeissblue)

sense.set_pixel(1,0, zeissblue)
sense.set_pixel(1,1, zeissblue)
sense.set_pixel(1,2, zeissblue)
sense.set_pixel(1,3, zeissblue)
sense.set_pixel(1,4, zeissblue)
sense.set_pixel(1,5, zeissblue)
sense.set_pixel(1,6, zeissblue)
sense.set_pixel(1,7, zeissblue)

sense.set_pixel(2,0, zeissblue)
sense.set_pixel(2,1, zeissblue)
sense.set_pixel(2,2, zeissblue)
sense.set_pixel(2,3, zeissblue)
sense.set_pixel(2,4, zeissblue)
sense.set_pixel(2,5, zeissblue)
sense.set_pixel(2,6, zeissblue)
sense.set_pixel(2,7, zeissblue)

sense.set_pixel(3,0, zeissblue)
sense.set_pixel(3,1, zeissblue)
sense.set_pixel(3,2, zeissblue)
sense.set_pixel(3,3, zeissblue)
sense.set_pixel(3,4, zeissblue)
sense.set_pixel(3,5, zeissblue)
sense.set_pixel(3,6, zeissblue)
sense.set_pixel(3,7, zeissblue)

sense.set_pixel(4,0, zeissblue)
sense.set_pixel(4,1, zeissblue)
sense.set_pixel(4,2, zeissblue)
sense.set_pixel(4,3, zeissblue)
sense.set_pixel(4,4, zeissblue)
sense.set_pixel(4,5, zeissblue)
sense.set_pixel(4,6, zeissblue)
sense.set_pixel(4,7, zeissblue)

sense.set_pixel(5,0, zeissblue)
sense.set_pixel(5,1, zeissblue)
sense.set_pixel(5,2, zeissblue)
sense.set_pixel(5,3, zeissblue)
sense.set_pixel(5,4, zeissblue)
sense.set_pixel(5,5, zeissblue)
sense.set_pixel(5,6, zeissblue)
sense.set_pixel(5,7, zeissblue)

sense.set_pixel(6,0, zeissblue)
sense.set_pixel(6,1, zeissblue)
sense.set_pixel(6,2, zeissblue)
sense.set_pixel(6,3, zeissblue)
sense.set_pixel(6,4, zeissblue)
sense.set_pixel(6,5, zeissblue)
sense.set_pixel(6,6, zeissblue)
sense.set_pixel(6,7, zeissblue)

sense.set_pixel(7,0, zeissblue)
sense.set_pixel(7,1, zeissblue)
sense.set_pixel(7,2, zeissblue)
sense.set_pixel(7,3, zeissblue)
sense.set_pixel(7,4, zeissblue)
sense.set_pixel(7,5, zeissblue)
sense.set_pixel(7,6, zeissblue)
sense.set_pixel(7,7, zeissblue)